version: '3.9'

networks:
  rb-network:
    driver: bridge
volumes:
  postgres-data:

services:
  rb-backend:
    container_name: rb-backend
    image: soranoshie/rbbackendcontainer:latest
    networks:
      - rb-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - rb-postgresdb
    env_file: backend/.env

  rb-postgresdb:
    container_name: rb-postgresdb
    image: postgres:15
    networks:
      - rb-network
    env_file: backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rb-frontend:
    build: frontend
    image: cr.yandex/crp1i88lts07dl1mahg7
    container_name: rb-frontend
    ports:
      # - '80:80' # If server-side rendering is disabled
      - '80:4000' # If server-side rendering is enabled
